-- Total Revenue Generated
-- Calculate total revenue
SELECT
    SUM(total_amount) AS Total_Revenue
FROM Orders
WHERE order_status NOT IN ('Cancelled');

-- Revenue by Category
-- Calculate revenue generated by each category
SELECT
    c.category_name,
    SUM(oi.subtotal) AS Revenue
FROM Categories c
JOIN Products p
    ON c.category_id = p.category_id
JOIN Order_Items oi
    ON p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY Revenue DESC;

-- Top 5 Selling Products
-- Display top selling products
SELECT
    p.product_name,
    SUM(oi.quantity) AS Total_Sold
FROM Products p
JOIN Order_Items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY Total_Sold DESC
LIMIT 5;

-- Most Active Customers
-- Display customers with highest number of orders
SELECT
    CONCAT(u.first_name,' ',u.last_name) AS Customer_Name,
    COUNT(o.order_id) AS Total_Orders
FROM Users u
JOIN Orders o
    ON u.user_id = o.user_id
GROUP BY u.user_id
ORDER BY Total_Orders DESC
LIMIT 5;

-- Highest Spending Customers
-- Display customers who spent the most
SELECT
    CONCAT(u.first_name,' ',u.last_name) AS Customer_Name,
    SUM(o.total_amount) AS Total_Spent
FROM Users u
JOIN Orders o
    ON u.user_id = o.user_id
WHERE o.order_status NOT IN ('Cancelled')
GROUP BY u.user_id
ORDER BY Total_Spent DESC
LIMIT 5;

-- Most Used Payment Method
-- Display most used payment methods
SELECT
    payment_method,
    COUNT(*) AS Usage_Count
FROM Payments
GROUP BY payment_method
ORDER BY Usage_Count DESC;

-- Average Order Value
-- Calculate average order value
SELECT
    AVG(total_amount) AS Average_Order_Value
FROM Orders;

-- Low Stock Products
-- Display low stock products
SELECT
    p.product_name,
    i.stock_quantity,
    i.reorder_level
FROM Products p
JOIN Inventory i
    ON p.product_id = i.product_id
WHERE i.stock_quantity <= i.reorder_level;

-- Products Never Ordered
-- Display products never ordered
SELECT
    p.product_name
FROM Products p
LEFT JOIN Order_Items oi
    ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

-- Products Never Reviewed
-- Display products without reviews
SELECT
    p.product_name
FROM Products p
LEFT JOIN Reviews r
    ON p.product_id = r.product_id
WHERE r.product_id IS NULL;

-- Highest Rated Products
-- Display highest rated products
SELECT
    p.product_name,
    AVG(r.rating) AS Average_Rating
FROM Products p
JOIN Reviews r
    ON p.product_id = r.product_id
GROUP BY p.product_id
ORDER BY Average_Rating DESC
LIMIT 5;

-- Orders by Status
-- Count orders by status
SELECT
    order_status,
    COUNT(*) AS Total_Orders
FROM Orders
GROUP BY order_status;

-- Revenue by Payment Method
-- Calculate revenue by payment method
SELECT
    payment_method,
    SUM(amount) AS Revenue
FROM Payments
WHERE payment_status = 'Successful'
GROUP BY payment_method
ORDER BY Revenue DESC;

-- Customers with Multiple Addresses
-- Display customers having multiple addresses
SELECT
    CONCAT(u.first_name,' ',u.last_name) AS Customer_Name,
    COUNT(a.address_id) AS Total_Addresses
FROM Users u
JOIN Addresses a
    ON u.user_id = a.user_id
GROUP BY u.user_id
HAVING COUNT(a.address_id) > 1;

-- Total Refund Amount
-- Calculate total refunded amount
SELECT
    SUM(refund_amount) AS Total_Refund
FROM Refunds;

-- Monthly Revenue Report
-- Calculate monthly revenue
SELECT
    MONTH(order_date) AS Month,
    SUM(total_amount) AS Revenue
FROM Orders
WHERE order_status NOT IN ('Cancelled')
GROUP BY MONTH(order_date)
ORDER BY Month;

-- Number of Products per Category
-- Count products in each category
SELECT
    c.category_name,
    COUNT(p.product_id) AS Total_Products
FROM Categories c
LEFT JOIN Products p
    ON c.category_id = p.category_id
GROUP BY c.category_name;

-- Average Rating per Category
-- Calculate average rating by category
SELECT
    c.category_name,
    AVG(r.rating) AS Average_Rating
FROM Categories c
JOIN Products p
    ON c.category_id = p.category_id
JOIN Reviews r
    ON p.product_id = r.product_id
GROUP BY c.category_name
ORDER BY Average_Rating DESC;

